version: '3.8'

services:
  postgres:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal

  drupal:
    depends_on:
      - postgres
    image: drupal:latest
    ports:
      - "8080:80"
    restart: always
    environment:
      DRUPAL_DB_HOST: postgres:5432
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal
      DRUPAL_DB_NAME: drupal

volumes:
  db_data: {}